alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias zan='/google/data/ro/teams/acl-zanzibar/tools/zan'
alias pod='/google/data/ro/teams/pod/tools/pod'
alias blaze-run='/google/src/head/depot/google3/devtools/blaze/scripts/blaze-run.sh'
